/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import application.model.Events;
import application.model.database.ModifyEvents;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jite
 */
public class Notification extends javax.swing.JFrame {

    Events e;
    static boolean dismiss;
    static boolean flag = true;

    //AudioStream as;
    /**
     * tCreates new form Notification
     *
     * @param e
     */
    public Notification(Events e) throws IOException {
        this.e = e;
        flag = true;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        titleLabel.setText(e.getEventName());
        jLabel1.setText(e.getOtherInfo());
        //InputStream in = new FileInputStream("/audio.au");
// Create an AudioStream object from the input stream.
        //as = new AudioStream(in);
// Use the static class member "player" from class AudioPlayer to play
// clip.
        //AudioPlayer.player.start(as);
        setVisible(true);
    }

    public static boolean generateNotification(Events e) {
        try {
            new Notification(e);
        } catch (IOException ex) {
            Logger.getLogger(Notification.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dismiss;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        snoozeButton = new javax.swing.JButton();
        dismissButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Notification");
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(350, 150));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(350, 150));
        setResizable(false);
        setSize(new java.awt.Dimension(350, 150));

        titleLabel.setFont(new java.awt.Font("Eras Bold ITC", 0, 25)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("title");

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("hulalala");

        snoozeButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        snoozeButton.setText("Snooze");
        snoozeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snoozeButtonActionPerformed(evt);
            }
        });

        dismissButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        dismissButton.setText("Dismiss");
        dismissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(dismissButton)
                .addGap(62, 62, 62)
                .addComponent(snoozeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(snoozeButton)
                    .addComponent(dismissButton))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void snoozeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snoozeButtonActionPerformed
        // TODO add your handling code here:
        dismiss = false;
        flag = false;
        e.setTime(LocalTime.now().plusMinutes(30));
        ModifyEvents.updateEvents(e);
        //AudioPlayer.player.stop(as);
        dispose();
    }//GEN-LAST:event_snoozeButtonActionPerformed

    private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
        // TODO add your handling code here:
        dismiss = true;
        flag = false;
        LocalDate d = e.getDate();
        switch (e.getRecurrence()) {
            case "None":
                e.setNotify(false);
                ModifyEvents.updateEvents(e);
                break;
            case "Yearly":
                e.setNotify(true);
                d = d.plusYears(1);
                e.setDate(d);
                ModifyEvents.updateEvents(e);
                break;
            case "Monthly":
                e.setNotify(true);
                d = d.plusMonths(1);
                e.setDate(d);
                ModifyEvents.updateEvents(e);
                break;
            case "Daily":
                e.setNotify(true);
                d = d.plusDays(1);
                e.setDate(d);
                ModifyEvents.updateEvents(e);
                break;
        }
        //AudioPlayer.player.stop(as);
        dispose();
    }//GEN-LAST:event_dismissButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    //  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dismissButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton snoozeButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
